# Generated by Django 3.0.2 on 2020-01-28 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='code',
            field=models.TextField(max_length=20, verbose_name='codigo'),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.URLField(unique=True, verbose_name='URL'),
        ),
    ]
