# Generated by Django 3.0.2 on 2020-02-06 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200206_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='usuario',
        ),
    ]
