# Generated by Django 3.0.2 on 2020-02-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200208_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='code',
            field=models.TextField(max_length=20, unique=True, verbose_name='codigo'),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.URLField(),
        ),
    ]
