# Generated by Django 3.0.2 on 2020-02-11 21:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200211_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='create',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creacion'),
            preserve_default=False,
        ),
    ]
