# Generated by Django 3.0.2 on 2020-02-07 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Link',
        ),
    ]
