# Generated by Django 3.0.2 on 2020-02-12 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_delete_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bio',
            new_name='notes',
        ),
    ]
